//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petslogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_friend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_friend()
        {
            this.tb_notification = new HashSet<tb_notification>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> friend_id { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual tb_user tb_user { get; set; }
        public virtual tb_user tb_user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_notification> tb_notification { get; set; }
    }
}
