//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petslogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_messages
    {
        public int id { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> since { get; set; }
        public Nullable<bool> show { get; set; }
    
        public virtual tb_user tb_user { get; set; }
        public virtual tb_user tb_user1 { get; set; }
    }
}
